// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package mysql

import (
	
	"time"
)

type AppSetting struct {
	AsID          int32          `json:"as_id"`
	AsKey         string         `json:"as_key"`
	AsValue       string         `json:"as_value"`
	AsDescription NullString `json:"as_description"`
	AsLastUpdated time.Time      `json:"as_last_updated"`
}

type Discount struct {
	DID          int32          `json:"d_id"`
	DCode        string         `json:"d_code"`
	DDescription NullString `json:"d_description"`
	DStartTime   NullTime   `json:"d_start_time"`
	DEndTime     NullTime   `json:"d_end_time"`
	DZoneTime    NullString `json:"d_zone_time"`
	DIsDisabled  bool           `json:"d_is_disabled"`
	DPriceType   string         `json:"d_price_type"`
	DValue       int32          `json:"d_value"`
}

type DiscountLink struct {
	DlID               int32         `json:"dl_id"`
	DlDiscountID       int32         `json:"dl_discount_id"`
	DlItemsID          NullInt32 `json:"dl_items_id"`
	DlItemsSubCategory NullInt32 `json:"dl_items_sub_category"`
	DlItemsCategory    NullInt32 `json:"dl_items_category"`
}

type GroupsPrivilege struct {
	GpID   int32          `json:"gp_id"`
	GpPath NullString `json:"gp_path"`
}

type GroupsPrivilegesLink struct {
	GplID                 int32 `json:"gpl_id"`
	GplGroupsUsersID      int32 `json:"gpl_groups_users_id"`
	GplGroupsPrivilegesID int32 `json:"gpl_groups_privileges_id"`
}

type GroupsUser struct {
	GuID          int32          `json:"gu_id"`
	GuName        string         `json:"gu_name"`
	GuDescription NullString `json:"gu_description"`
}

type GroupsUsersLink struct {
	GulID      int32 `json:"gul_id"`
	GulUserID  int32 `json:"gul_user_id"`
	GulGroupID int32 `json:"gul_group_id"`
}

type Item struct {
	IID          int32          `json:"i_id"`
	ITitle       string         `json:"i_title"`
	IDescription NullString `json:"i_description"`
	IPrice       string         `json:"i_price"`
	IQuantity    NullInt32  `json:"i_quantity"`
	IPictureUrl  NullString `json:"i_picture_url"`
	IFilePath    NullString `json:"i_file_path"`
	IIsDisabled  bool           `json:"i_is_disabled"`
	IReleaseDate time.Time      `json:"i_release_date"`
}

type ItemsCategory struct {
	IcID          int32          `json:"ic_id"`
	IcName        string         `json:"ic_name"`
	IcDescription NullString `json:"ic_description"`
	IcPictureUrl  NullString `json:"ic_picture_url"`
}

type ItemsCategoryLink struct {
	IclID                 int32 `json:"icl_id"`
	IclItemsSubCategoryID int32 `json:"icl_items_sub_category_id"`
	IclItemsCategoryID    int32 `json:"icl_items_category_id"`
}

type ItemsReview struct {
	IrID       int32  `json:"ir_id"`
	IrUserID   int32  `json:"ir_user_id"`
	IrItemsID  int32  `json:"ir_items_id"`
	IrComments string `json:"ir_comments"`
	IrStars    int32  `json:"ir_stars"`
}

type ItemsSubCategory struct {
	IscID          int32          `json:"isc_id"`
	IscName        string         `json:"isc_name"`
	IscDescription NullString `json:"isc_description"`
	IscPictureUrl  NullString `json:"isc_picture_url"`
}

type ItemsSubCategoryLink struct {
	IsclID            int32 `json:"iscl_id"`
	IsclItemsID       int32 `json:"iscl_items_id"`
	IsclSubCategoryID int32 `json:"iscl_sub_category_id"`
}

type User struct {
	UID           int32     `json:"u_id"`
	UEmail        string    `json:"u_email"`
	UUid          string    `json:"u_uid"`
	URegisterDate time.Time `json:"u_register_date"`
	UIsDisabled   bool      `json:"u_is_disabled"`
}

type UsersBasket struct {
	UbID        int32     `json:"ub_id"`
	UbUserID    int32     `json:"ub_user_id"`
	UbItemsID   int32     `json:"ub_items_id"`
	UbTimeAdded time.Time `json:"ub_time_added"`
	UbQuantity  int32     `json:"ub_quantity"`
}

type UsersWishlist struct {
	WlID         int32         `json:"wl_id"`
	WlUserID     int32         `json:"wl_user_id"`
	WlItemsID    NullInt32 `json:"wl_items_id"`
	WlTimesAdded time.Time     `json:"wl_times_added"`
}
